[package]
name = "lego_ble_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = { version = "0.9.0", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
